quiz/urls.py
from django.urls import path

from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboar'),
    path('teste/<int:categoria_id>', views.TesteView.as_view(), name='teste'),

    path('lista/', views.CategoriaViewSet.as_view(), name='lista'),
    path('adm/', views.CategoriaAdminViewSet.as_view({'get': 'list'}), name='adm-lista'),
    path('questao/', views.QuestaoAdminViewSet.as_view({'get': 'list'}), name='questao-lista'),

]

quizproject/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

# Rotas dos apps
from quiz.views import CategoriaAdminViewSet, QuestaoAdminViewSet

api_router = routers.DefaultRouter()
api_router.register(r"categoria", CategoriaAdminViewSet)
api_router.register(r"questao", QuestaoAdminViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('api_quiz/', include(api_router.urls)),
    path('quiz/', include('quiz.urls')),

]

quiz/models.py
from django.db import models

# Create your models here.
from quiz.choices import CORRETAS


class Categoria(models.Model):
    categoria = models.CharField(verbose_name=("categoria"), max_length=250, blank=True, unique=True, null=True)

    class Meta:
        verbose_name = ("Categoria")
        verbose_name_plural = ("Categoria")

    def __str__(self):
        return self.categoria


class Questao(models.Model):
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    questao = models.CharField(max_length=700, blank=False, null=False, verbose_name='Questão')
    opicao_a = models.CharField(max_length=500, blank=False, null=False, verbose_name='Opicao A')
    opicao_b = models.CharField(max_length=500, blank=False, null=False, verbose_name='Opicao B')
    opicao_c = models.CharField(max_length=500, blank=False, null=False, verbose_name='Opicao C')
    correta = models.CharField(max_length=2, blank=False, null=False, choices=CORRETAS)

    class Meta:
        verbose_name = ("Questão")
        verbose_name_plural = ("Questões")

    def __str__(self):
        return self.questao

quiz/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.forms import widgets


class QuizForm(forms.Form):

    def __init__(self, *args, **kwargs):
        questoes = kwargs.pop('questoes')  # pop questoes array from kwargs
        super().__init__(*args, **kwargs)
        if questoes:
            for questao in questoes:  # add a form field for each questao
                CHOICES = (
                    ('A', questao.opicao_a),
                    ('B', questao.opicao_b),
                    ('C', questao.opicao_c),
                )
                self.fields[questao.questao] = forms.ChoiceField(required=False, choices=CHOICES,
                                                                           widget=widgets.RadioSelect)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    def answers(self):  # return questaos and answers for result processing
        for name, questao in self.cleaned_data.items():
            yield (name, questao)

quiz/views.py
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin
# Create your views here.
from django.views.generic import TemplateView
from rest_framework import viewsets, generics

from quiz.forms import QuizForm
from quiz.models import Categoria, Questao
from quiz.serializer import CategoriaSerializer, QuestaoSerializer
from user.models import Profile


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'quiz/categoria_list.html'
    model = Categoria

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['categoria_list'] = Categoria.objects.all()
        return context

class TesteView(LoginRequiredMixin, TemplateView):
    template_name = 'quiz/teste.html'
    model = Questao

    def get_questoes(self):
        profile = Profile.objects.get(user=self.request.user)
        questoes = Questao.objects.filter(categoria__id=self.kwargs['categoria_id']).exclude(questao__in=[item.questao for item in profile.questao_corretas.all()]).order_by('?')[0:10]
        return questoes

    def get_context_data(self, **kwargs):
        form = QuizForm(None, questoes=self.get_questoes())

        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        form = QuizForm(self.request.POST, questoes=self.get_questoes())
        profile_user = Profile.objects.get(user=request.user)

        if form.is_valid():
            questions_list = []
            answers_list = []
            for (quiz_question, answer) in form.answers():
                questao = Questao.objects.filter(questao=quiz_question)[0]
                if questao.correta == answer:
                    profile_user.adicionar_pontos()
                    profile_user.questao_corretas.add(questao)
                else:
                    profile_user.remove_pontos()
                    profile_user.questao_erradas.add(questao)

            flag = True

        # if flag:
        #     request.session.clear()
        #     return redirect('finish')
        # # content = zip(questions, form)
        # # request.session['questions'] = id_list
        # context = {'content': 'content'}
        # return render(request, 'quiz.html', context)

        return self.get(request, *args, **kwargs)


class CategoriaViewSet(LoginRequiredMixin, generics.ListAPIView):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer


class CategoriaAdminViewSet(LoginRequiredMixin, SuperuserRequiredMixin, viewsets.ModelViewSet):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer
    filterset_fields = ['categoria']


class QuestaoAdminViewSet(LoginRequiredMixin, SuperuserRequiredMixin, viewsets.ModelViewSet):
    queryset = Questao.objects.all()
    serializer_class = QuestaoSerializer
    filterset_fields = ['categoria']


# class CategoriaAdminDetailsView(LoginRequiredMixin, SuperuserRequiredMixin, viewsets.ModelViewSet):
#     queryset = Categoria.objects.all()
#     serializer_class = CategoriaSerializer
#     filterset_fields = ['categoria']

#
# class CategoriaViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
#     queryset = Categoria.objects.all()
#     serializer_class = CategoriaSerializer


# class CategoriaQuizViewSet(LoginRequiredMixin, viewsets.ViewSet):
#     queryset = Categoria.objects.all()
#     serializer_class = CategoriaSerializer
#     template_name = 'quiz/categoria_list.html'
#
#     def list(self, request):
#         serializer = CategoriaSerializer()
#         return JsonResponse(serializer.data)

quiz/templates/quiz/categoria_list.html
{% extends 'base.html' %}

{% load static %}

{#{% block topbar %}#}
{##}
{#{% endblock %}#}
{##}
{% block container %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Quiz</h1>

        <div class="row">


            <div class="col-lg-12">

                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Escolha sua categoria</h6>
                    </div>
                    <div class="card-body">
                        <ul>
                            {% for categoria in categoria_list %}
                                <div class="my-2"></div>

                                <a href="{% url 'quiz:teste' categoria.id %}" class="btn btn-light btn-icon-split">
                                        <span class="icon text-gray-600">
                                            <i class="fas fa-arrow-right"></i>
                                        </span>
                                    <span class="text">{{ categoria }}</span>
                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

quiz/templates/quiz/teste.html
{% extends 'base.html' %}

{% load static %}

{#{% block topbar %}#}
{##}
{#{% endblock %}#}
{##}
{% block container %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Quiz</h1>

        <div class="row">


            <div class="col-lg-12">

                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Escolha sua categoria</h6>
                    </div>
                    <div class="card-body">
                            {% include 'quiz/includes/form.html'%}

                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}