quiz/urls.py
from django.urls import path

from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboar'),
    path('teste/<int:categoria_id>', views.TesteView.as_view(), name='teste'),

    path('lista/', views.CategoriaViewSet.as_view(), name='lista'),
    path('adm/', views.CategoriaAdminViewSet.as_view({'get': 'list'}), name='adm-lista'),
    path('questao/', views.QuestaoAdminViewSet.as_view({'get': 'list'}), name='questao-lista'),

]

quizproject/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

# Rotas dos apps
from quiz.views import CategoriaAdminViewSet, QuestaoAdminViewSet

api_router = routers.DefaultRouter()
api_router.register(r"categoria", CategoriaAdminViewSet)
api_router.register(r"questao", QuestaoAdminViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('api_quiz/', include(api_router.urls)),
    path('quiz/', include('quiz.urls')),

]

user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from . import views

app_name = 'user'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('home/', views.logged_in, name="logged_in"),

    path('criar_user/', views.BasicCreateUserView.as_view(), name='criar-user'),
    path('profile/', views.ProfileListView.as_view(), name='profile'),

    # path('home/', views.Home.as_view(), name='home'),
    # path('delete/', views.BasicDeleteUser.as_view(), name='delete'),

    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='user/redefinir_senha.html',
            email_template_name='user/password_reset_email.html',
            subject_template_name='user/password_reset_subject.txt',
            success_url=reverse_lazy('user:password_reset_done')
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                                    success_url=reverse_lazy('user:login')),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='user/password_change.html',
                                                                       success_url=reverse_lazy('user:login')),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html', ),
        name='password_change_done'),

]

user/models.py
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from quiz.models import Questao

from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_pontos = models.IntegerField(blank=True, default=0)
    sequencial = models.IntegerField(blank=True, default=1)
    questao_corretas = models.ManyToManyField(Questao, related_name='questao_corretas', blank=True)
    questao_erradas = models.ManyToManyField(Questao, related_name='questao_erradas', blank=True)
    pontos = models.IntegerField(blank=True, default=0)

    def adicionar_pontos(self):
        self.total_pontos += 1
        self.save()

    def remove_pontos(self):
        if self.total_pontos != 0:
            self.total_pontos -= 1
            self.save()

    def att_sequncial(queryset):
        sequencial = 1
        for item in queryset:
            print(queryset)
            item.sequencial = sequencial
            item.save()
            sequencial += 1

    def soma_de_pontos(soma):
        if soma >= 0:
            return soma
        else:
            return 0

    def att_pontuacao(lista_profile, id, categoria=False):
        for item in lista_profile:
            pontos_q_certas = Profile.objects.filter(questao_corretas__categoria__id__in=id, user=item.user).count()
            pontos_q_erradas = Profile.objects.filter(questao_erradas__categoria__id__in=id, user=item.user).count()
            soma = pontos_q_certas - pontos_q_erradas
            print(soma)
            if categoria:
                item.pontos = Profile.soma_de_pontos(soma)
                item.save()
            else:
                item.pontos = item.total_pontos
                item.save()


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput(), help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.' )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).count() > 0:
            raise forms.ValidationError(u'This email address is already registered.')
        return email


class UserInformationUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

user/views.py
from braces.views import LoginRequiredMixin
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django_filters.views import FilterView

from user.filters import ProfileFilter
from user.forms import SignUpForm
from user.models import User, Profile


# Create your views here.
class BasicCreateUserView(CreateView):
    template_name = 'user/criar_user.html'
    form_class = SignUpForm
    model = User

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('quiz:dashboar')
        else:
            return render(request, 'user/signup.html', {'form': form})


def logged_in(request):
   if request.user.is_superuser:
       return redirect('/api_quiz')
   else:
      return redirect('quiz:dashboar')


# Create your views here.


class ProfileListView(LoginRequiredMixin, FilterView):
    template_name = 'profile/tabela.html'
    model = Profile
    filterset_class = ProfileFilter

    def get_queryset(self):
        queryset = Profile.objects.filter(user__is_superuser=False).order_by('-total_pontos').distinct()
        Profile.att_sequncial(queryset)
        Profile.att_pontuacao(queryset, '', categoria=False)

        return queryset

user/templates/user/base_user.html
{% load static %}
{% load form_tags %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    {% block stylesheet %}{% endblock %}
    <style>
        .bg-image {
            width: auto;
            height: auto;
            background: url('{% static 'img/neon-lettering-quiz-sobre-um-fundo-de-parede-de-tijolo-inscricao-multicolorida_100690-71.jpg' %}');
        }

    </style>
</head>

<body class="bg-gradient-primary" style="background:url('{% static 'img/19629.jpg' %}')">

<div class="container">
    {% block container %}

    {% endblock container %}

</div>
{% block javascript %}{% endblock %}

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>

user/templates/user/criar_user.html
{% extends 'user/base_user.html' %}

{% load static %}



{% block container %}
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Crie a sua conta aqui!</h1>
                            </div>
                            <form method="post" novalidate>
                                {% csrf_token %}
                                {% include 'user/includes/form.html' %}
                                <button type="submit"  class="btn btn-primary btn-user btn-block">
                                    Registar Conta
                                </button>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small " href="{% url 'user:password_reset' %}">Esqueceu a senha?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="{% url 'user:login' %}">já tem uma conta? Conecte-se!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

user/templates/user/login.html
{% extends 'user/base_user.html' %}

{% load static %}



{% block container %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bem vindo ao Quiz!
                                        </h1>
                                    </div>
                                    <form method="post" novalidate>
                                        {% csrf_token %}

                                        {% include 'user/includes/form.html' %}

                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>

                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'user:password_reset' %}">Esqueceu a senha?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'user:criar-user' %}">Crie a sua conta aqui!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>


{% endblock %}

user/templates/user/password_change.html
{% extends 'base.html' %}

{% load static %}



{% block container %}

        <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card ">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
{#                            <div class="col-lg-6 d-none d-lg-block bg-image"></div>#}
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Change password
                                        </h1>
                                    </div>
                                    <form method="post" novalidate>
                                        {% csrf_token %}

                                        {% include 'user/includes/form.html' %}

                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Change password
                                        </button>

                                    </form>
                                    <hr>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>




{#    <li class="breadcrumb-item active">Change password</li>#}
{#    <div class="row">#}
{#        <div class="col-lg-6 col-md-8 col-sm-10">#}
{#            <form method="post" novalidate>#}
{#                {% csrf_token %}#}
{#                {% for field in form %}#}
{#                    <div class="form-group">#}
{#                        {{ field.label_tag }}{% if field.field.required %}*{% endif %}#}
{#                        {{ field }}#}
{#                        {% for error in field.errors %}#}
{#                            <small class="form-text " style="color: red">#}
{##}
{#                                {{ error }} </small>#}
{##}
{#                        {% endfor %}#}
{#                        {% if field.help_text %}#}
{#                            <small class="form-text text-muted">#}
{#                                {{ field.help_text|safe }}#}
{#                            </small>#}
{#                        {% endif %}#}
{#                    </div>#}
{#                {% endfor %}#}
{#                <button type="submit" class="btn btn-success">Change password</button>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{% endblock %}

user/templates/user/password_change_done.html
{% extends 'user/base_user.html' %}

{% load static %}



{% block container %}
  <li class="breadcrumb-item"><a href="{% url 'user:password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>

  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="#" class="btn btn-secondary">Return to home page</a>


{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'user/base_user.html' %}

{% load static %}



{% block container %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'user:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'user/base_user.html' %}

{% load static %}



{% block container %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'user/includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'user:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'user/base_user.html' %}

{% load static %}



{% block container %}

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Redefina sua senha
                                        </h1>
                                        <p class="mb-4">Verifique seu e-mail para obter um link para redefinir sua
                                            senha. Se não aparecer em alguns minutos, verifique sua pasta de spam.</p>
                                    </div>


                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'user:login' %}">Volta login?</a>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

user/templates/user/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake while trying
to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team

user/templates/user/redefinir_senha.html
{% extends 'user/base_user.html' %}
{% load form_tags %}
{% load form_tags widget_tweaks %}

{% load static %}



{% block container %}
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Esqueceu sua senha?</h1>
                                    <p class="mb-4">Nós entendemos, coisas acontecem. Basta inserir seu endereço de
                                        e-mail abaixo e enviaremos um link para redefinir sua senha!</p>
                                </div>


                                <form method="post" novalidate>
                                    {% csrf_token %}
                                    {% include 'user/includes/form.html' %}

                                    <button type="submit" class="btn btn-primary btn-user btn-block">Enviar e-mail de
                                        redefinição de senha

                                    </button>
                                </form>


                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'user:criar-user' %}">Crie a sua conta aqui!</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'user:login' %}">já tem uma conta? Conecte-se!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

user/templates/user/signup.html
{% extends 'user/base_user.html' %}

{% load static %}



{% block container %}
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Crie a sua conta aqui!</h1>
                            </div>
                            <form method="post" novalidate>
                                {% csrf_token %}
                                {% include 'user/includes/form.html' %}
                                <button type="submit"  class="btn btn-primary btn-user btn-block">
                                    Registar Conta
                                </button>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small " href="{% url 'user:password_reset' %}">Esqueceu a senha?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="{% url 'user:login' %}">já tem uma conta? Conecte-se!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}