quiz/urls.py
from django.urls import path

from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboar'),
    path('teste/<int:categoria_id>', views.TesteView.as_view(), name='teste'),

    path('lista/', views.CategoriaViewSet.as_view(), name='lista'),
    path('adm/', views.CategoriaAdminViewSet.as_view({'get': 'list'}), name='adm-lista'),
    path('questao/', views.QuestaoAdminViewSet.as_view({'get': 'list'}), name='questao-lista'),

]

quizproject/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

# Rotas dos apps
from quiz.views import CategoriaAdminViewSet, QuestaoAdminViewSet

api_router = routers.DefaultRouter()
api_router.register(r"categoria", CategoriaAdminViewSet)
api_router.register(r"questao", QuestaoAdminViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('api_quiz/', include(api_router.urls)),
    path('quiz/', include('quiz.urls')),

]

user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from . import views

app_name = 'user'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('home/', views.logged_in, name="logged_in"),

    path('criar_user/', views.BasicCreateUserView.as_view(), name='criar-user'),
    path('profile/', views.ProfileListView.as_view(), name='profile'),

    # path('home/', views.Home.as_view(), name='home'),
    # path('delete/', views.BasicDeleteUser.as_view(), name='delete'),

    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='user/redefinir_senha.html',
            email_template_name='user/password_reset_email.html',
            subject_template_name='user/password_reset_subject.txt',
            success_url=reverse_lazy('user:password_reset_done')
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                                    success_url=reverse_lazy('user:login')),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='user/password_change.html',
                                                                       success_url=reverse_lazy('user:login')),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html', ),
        name='password_change_done'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Blank</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css">

    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" type="text/css">

    {% block stylesheet %}{% endblock %}


</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <!-- End of Sidebar -->
    {% include 'menu.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">
            {% include 'topbar.html' %}

            {% block container %}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

                </div>
                <!-- /.container-fluid -->
            {% endblock %}

        </div>

        <!-- End of Main Content -->

        <!-- Footer -->
        {% block footer %}

            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
        {% endblock footer %}

        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
{#    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"#}
{#        aria-hidden="true">#}
{#        <div class="modal-dialog" role="document">#}
{#            <div class="modal-content">#}
{#                <div class="modal-header">#}
{#                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>#}
{#                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">#}
{#                        <span aria-hidden="true">×</span>#}
{#                    </button>#}
{#                </div>#}
{#                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>#}
{#                <div class="modal-footer">#}
{#                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>#}
{#                    <a class="btn btn-primary" href="login.html">Logout</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}


{% block javascript %}{% endblock %}

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
<script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>

<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
</body>

</html>

templates/base_tables.html
{% extends 'base.html' %}

{% block container %}


    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
            For more information about DataTables, please visit the <a target="_blank"
                                                                       href="https://datatables.net">official
                DataTables documentation</a>.</p>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                                    {% block search_form %}

                                            {% endblock %}

                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            {% block grid_header %}
                            {% endblock %}
                        </tr>
                        </thead>
                        <tbody>
                        {% block include_table %}
                            {% for item in object_list %}
                                <tr class="kt-datatable__row" style="left: 0px;" id="tr_{{ item.id }}">
                                    {% block grid_item %}
                                    {% endblock %}
                                </tr>
                            {% endfor %}
                        {% endblock %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="../static/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="../static/vendor/jquery/jquery.min.js"></script>
    <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="../static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="../static/js/sb-admin-2.min.js"></script>

</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="../static/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <a href="index.html" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </a>
                                        <hr>
                                        <a href="index.html" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>
                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="../static/vendor/jquery/jquery.min.js"></script>
    <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="../static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="../static/js/sb-admin-2.min.js"></script>

</body>

</html>

templates/menu.html
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'quiz:dashboar' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:profile' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Ranck</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
{#            <div class="sidebar-heading">#}
{#                Interface#}
{#            </div>#}
{##}
{#            <!-- Nav Item - Pages Collapse Menu -->#}
{#            <li class="nav-item">#}
{#                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"#}
{#                    aria-expanded="true" aria-controls="collapseTwo">#}
{#                    <i class="fas fa-fw fa-cog"></i>#}
{#                    <span>Components</span>#}
{#                </a>#}
{#                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">#}
{#                    <div class="bg-white py-2 collapse-inner rounded">#}
{#                        <h6 class="collapse-header">Custom Components:</h6>#}
{#                        <a class="collapse-item" href="buttons.html">Buttons</a>#}
{#                        <a class="collapse-item" href="cards.html">Cards</a>#}
{#                    </div>#}
{#                </div>#}
{#            </li>#}
{##}
{#            <!-- Nav Item - Utilities Collapse Menu -->#}
{#            <li class="nav-item">#}
{#                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"#}
{#                    aria-expanded="true" aria-controls="collapseUtilities">#}
{#                    <i class="fas fa-fw fa-wrench"></i>#}
{#                    <span>Utilities</span>#}
{#                </a>#}
{#                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"#}
{#                    data-parent="#accordionSidebar">#}
{#                    <div class="bg-white py-2 collapse-inner rounded">#}
{#                        <h6 class="collapse-header">Custom Utilities:</h6>#}
{#                        <a class="collapse-item" href="utilities-color.html">Colors</a>#}
{#                        <a class="collapse-item" href="utilities-border.html">Borders</a>#}
{#                        <a class="collapse-item" href="utilities-animation.html">Animations</a>#}
{#                        <a class="collapse-item" href="utilities-other.html">Other</a>#}
{#                    </div>#}
{#                </div>#}
{#            </li>#}
{##}
{#            <!-- Divider -->#}
{#            <hr class="sidebar-divider">#}
{##}
{#            <!-- Heading -->#}
{#            <div class="sidebar-heading">#}
{#                Addons#}
{#            </div>#}
{##}
{#            <!-- Nav Item - Pages Collapse Menu -->#}
{#            <li class="nav-item active">#}
{#                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"#}
{#                    aria-controls="collapsePages">#}
{#                    <i class="fas fa-fw fa-folder"></i>#}
{#                    <span>Pages</span>#}
{#                </a>#}
{#                <div id="collapsePages" class="collapse show" aria-labelledby="headingPages"#}
{#                    data-parent="#accordionSidebar">#}
{#                    <div class="bg-white py-2 collapse-inner rounded">#}
{#                        <h6 class="collapse-header">Login Screens:</h6>#}
{#                        <a class="collapse-item" href="login.html">Login</a>#}
{#                        <a class="collapse-item" href="register.html">Register</a>#}
{#                        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>#}
{#                        <div class="collapse-divider"></div>#}
{#                        <h6 class="collapse-header">Other Pages:</h6>#}
{#                        <a class="collapse-item" href="404.html">404 Page</a>#}
{#                        <a class="collapse-item active" href="blank.html">Blank Page</a>#}
{#                    </div>#}
{#                </div>#}
{#            </li>#}
{##}
{#            <!-- Nav Item - Charts -->#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="charts.html">#}
{#                    <i class="fas fa-fw fa-chart-area"></i>#}
{#                    <span>Charts</span></a>#}
{#            </li>#}
{##}
{#            <!-- Nav Item - Tables -->#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="tables.html">#}
{#                    <i class="fas fa-fw fa-table"></i>#}
{#                    <span>Tables</span></a>#}
{#            </li>#}
{##}
{#            <!-- Divider -->#}
{#            <hr class="sidebar-divider d-none d-md-block">#}
{##}
{#            <!-- Sidebar Toggler (Sidebar) -->#}
{#            <div class="text-center d-none d-md-inline">#}
{#                <button class="rounded-circle border-0" id="sidebarToggle"></button>#}
{#            </div>#}

        </ul>

templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="../static/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form class="user">
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="exampleFirstName"
                                            placeholder="First Name">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" id="exampleLastName"
                                            placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Email Address">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Repeat Password">
                                    </div>
                                </div>
                                <a href="login.html" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </a>
                                <hr>
                                <a href="index.html" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Register with Google
                                </a>
                                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                    <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                                </a>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="login.html">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="../static/vendor/jquery/jquery.min.js"></script>
    <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="../static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="../static/js/sb-admin-2.min.js"></script>

</body>

</html>